In [2]:
import pandas as pd

print("Pandas siap digunakan!")

# Coba bikin data simpel
df = pd.DataFrame({'Target': ['Belajar AI', 'PKL Juli'], 'Status': ['Proses', 'Siap']})
df

Pandas siap digunakan!

       Target  Status
0  Belajar AI  Proses
1    PKL Juli    Siap

In [6]:
import pandas as pd

print("Pandas siap digunakan!")

df = pd.DataFrame({
    'Target': ['Belajar AI', 'PKL Juli'],
    'Status': ['Proses', 'Siap'],
    'Deadline': ['Hari ini', 'Bulan Juli'] # Tambahkan ini
})
df

Pandas siap digunakan!

       Target  Status    Deadline
0  Belajar AI  Proses    Hari ini
1    PKL Juli    Siap  Bulan Juli

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Target    2 non-null      str
 1   Status    2 non-null      str
 2   Deadline  2 non-null      str
dtypes: str(3)
memory usage: 226.0 bytes

In [7]:
df['Progress_Persen'] = [20, 100] # Menambah kolom angka
print(df.describe())

       Progress_Persen
count         2.000000
mean         60.000000
std          56.568542
min          20.000000
25%          40.000000
50%          60.000000
75%          80.000000
max         100.000000

In [8]:
df['Target']

0    Belajar AI
1      PKL Juli
Name: Target, dtype: str

In [9]:
df['Status']

0    Proses
1      Siap
Name: Status, dtype: str